version: "3"
services:
  web:
    image: nginx:latest
    volumes:
      - ./setup-nginx-docker.sh:/app/setup-nginx-docker.sh
    entrypoint: /app/setup-nginx-docker.sh
    ports:
      - 80:80
    depends_on:
      - chat-api
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - /data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: always

  redis-cache:
    image: redis:latest
    volumes:
      - /data/redis:/data
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 5671:5671
      - 15692:15692
    restart: always

  chat-api:
    depends_on:
      - mongodb
      - redis-cache
      - rabbitmq
    image: droncogene/popchat-api:latest
    pull_policy: always
    deploy:
      replicas: 2
    environment:
      - DB_HOST=mongodb
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - APP_HOST=0.0.0.0
    hostname: chat-api
    ports:
      - 8000-8001:8000
    restart: always
    secrets:
      - env_file

secrets:
  env_file:
    file: ".env"
